"""55+ AI-tell taxonomy and pattern definitions.

Synthesized from:
- blader/humanizer (Wikipedia "Signs of AI writing", MIT)
- HUMANIZED_CONTENT_GUARDRAILS.md (55+ taxonomy, two-pass pipeline)
- Observations of AI-generated text across 1,690 eval samples
"""

import re

EM_DASH = "\u2014"
EN_DASH = "\u2013"

DASH_REPLACEMENTS = {
    EM_DASH: " - ",
    EN_DASH: "-",
}

BANNED_WORDS: dict[str, str] = {
    "delve": "explore, examine, inspect, look at",
    "delving": "exploring, examining, investigating",
    "tapestry": "structure, collection, system, setup",
    "testament": "proof, evidence, demonstration",
    "beacon": "benchmark, standard, reference point",
    "paramount": "critical, essential, crucial, key",
    "pivotal": "key, central, crucial, important",
    "seamless": "clean, direct, smooth, integrated",
    "seamlessly": "cleanly, directly, smoothly",
    "revolutionize": "change, overhaul, improve, redesign",
    "revolutionizes": "changes, overhauls, improves, redesigns",
    "revolutionizing": "changing, improving, transforming",
    "foster": "build, encourage, create, support",
    "fostering": "building, encouraging, supporting",
    "spearhead": "lead, start, drive, build",
    "spearheading": "leading, starting, driving",
    "groundbreaking": "major shift, breakthrough, big improvement",
    "game-changer": "major shift, big improvement, breakthrough",
    "gamechanger": "major shift, big improvement, breakthrough",
    "holistic": "complete, comprehensive, thorough",
    "intricate": "complex, detailed, involved",
    "nuanced": "detailed, specific, subtle",
    "plethora": "many, dozens, multiple",
    "myriad": "many, numerous, varied",
    "harnessing": "using, running, applying",
    "supercharge": "speed up, accelerate, optimize",
    "elevate": "improve, raise, boost",
    "actually": "(cut - filler)",
    "additionally": "also, plus, or just start the sentence",
    "crucial": "important, necessary, key",
    "emphasizing": "(cut - superficial -ing phrase)",
    "enduring": "lasting, long-term",
    "enhance": "improve, strengthen",
    "enhanced": "improved, strengthened",
    "enhancing": "improving, strengthening",
    "garner": "attract, earn, collect",
    "highlight": "show, reveal, demonstrate",
    "highlights": "shows, reveals, demonstrates",
    "interplay": "interaction, relationship",
    "intricacies": "details, complexities",
    "landscape": "field, market, area, space",
    "showcase": "show, present, demonstrate",
    "showcases": "shows, presents, demonstrates",
    "showcasing": "showing, presenting",
    "underscore": "show, prove, emphasize",
    "underscores": "shows, proves, emphasizes",
    "valuable": "useful, important, practical",
    "vibrant": "active, lively, busy",
    "realm": "area, field, space",
    "leverage": "use, apply, run",
    "leveraging": "using, applying",
    "unlock": "enable, allow, make possible",
    "unlocking": "enabling, allowing",
    "dive": "examine, analyze, look at",
    "robust": "strong, reliable, solid",
    "cutting-edge": "modern, current, latest",
    "state-of-the-art": "modern, advanced, current",
    "transformative": "significant, major, impactful",
    "empower": "enable, allow, help",
    "empowering": "enabling, allowing, helping",
    "empowers": "enables, allows, helps",
    "streamline": "simplify, speed up, clean up",
    "streamlining": "simplifying, speeding up",
    "synergy": "cooperation, alignment, fit",
    "synergies": "cooperation, alignment",
}

BANNED_PHRASES: list[tuple[str, str]] = [
    (r"\bin the ever[- ]evolving landscape\b", "Cut entirely or state the specific technical change."),
    (r"\bin today'?s fast[- ]paced (digital )?world\b", "Cut or replace with the specific context."),
    (r"\bit is important to (note|remember|consider)\b", "State the fact directly without preamble."),
    (r"\bit is worth (noting|mentioning)\b", "State the fact directly."),
    (r"\bat its core\b", "Describe the mechanism directly."),
    (r"\bstands as a testament\b", "Use 'proves' or 'shows'."),
    (r"\bstands as a\b", "Use 'is' instead."),
    (r"\bserves as a\b", "Use 'is' instead."),
    (r"\bdive deep into\b", "Use 'examine', 'analyze', or 'break down'."),
    (r"\ba rich tapestry of\b", "Describe the actual elements directly."),
    (r"\bin conclusion\b", "Cut. Let conclusions stand as technical takeaways."),
    (r"\bto (sum up|wrap things up|summarize)\b", "Cut conversational summary cliches."),
    (r"\ball in all\b", "Cut."),
    (r"\bgreat question!?\b", "Cut sycophantic chat filler. Answer directly."),
    (r"\bcertainly!?\b", "Cut."),
    (r"\bspot on!?\b", "Cut."),
    (r"\bunlock the potential\b", "Use 'enable' or 'make possible'."),
    (r"\bonly time will tell\b", "Cut or state the specific uncertainty."),
    (r"\bone thing is certain\b", "Cut or state the specific claim."),
    (r"\bthe future looks bright\b", "Cut or state the specific plan."),
    (r"\bexciting times lie ahead\b", "Cut."),
    (r"\blet'?s (dive in|explore|break this down)\b", "Cut. Start with the content directly."),
    (r"\bhere'?s what you need to know\b", "Cut. Present the information directly."),
    (r"\bwithout further ado\b", "Cut."),
    (r"\bnow let'?s look at\b", "Cut. Transition naturally."),
    (r"\bi hope this helps\b", "Cut."),
    (r"\blet me know if\b", "Cut."),
    (r"\bthe real question is\b", "Just ask the question."),
    (r"\bwhat really matters\b", "State the priority directly."),
    (r"\bfundamentally\b", "Cut or rewrite without the qualifier."),
    (r"\bthe deeper (issue|question|problem)\b", "State the issue directly."),
    (r"\bthe heart of the matter\b", "State the core point directly."),
    (r"\bin order to\b", "Use 'to'."),
    (r"\bdue to the fact that\b", "Use 'because'."),
    (r"\bat this point in time\b", "Use 'now'."),
    (r"\bin the event that\b", "Use 'if'."),
    (r"\bhas the ability to\b", "Use 'can'."),
    (r"\bit is important to note that\b", "Cut. State the fact."),
    (r"\bdespite (its|these) challenges\b", "Cut or state the specific challenge and response."),
    (r"\bfaces several challenges\b", "Name the specific challenges."),
    (r"\bfuture outlook\b", "Cut or state specific plans."),
    (r"\bnot only .{0,40} but also\b", "Rewrite as a single direct statement."),
    (r"\bit'?s not just about .{0,40} it'?s\b", "Rewrite as a single direct statement."),
    (r"\bit'?s not merely .{0,40} it'?s\b", "Rewrite as a single direct statement."),
]

TRIADIC_PATTERN = re.compile(
    r"\b(\w{3,15}),\s+(\w{3,15}),\s+and\s+(\w{3,15})\b"
)

SYCOPHANTIC_OPENERS = [
    "great question",
    "excellent question",
    "wonderful question",
    "you're absolutely right",
    "you are absolutely right",
    "spot on",
    "that's a great point",
    "that is a great point",
    "absolutely!",
    "of course!",
    "certainly!",
    "sure thing!",
]

AI_TELL_TAXONOMY: list[dict] = [
    {"id": "PUNCT-01", "category": "Punctuation", "name": "Em-dash overuse", "pattern": "---"},
    {"id": "PUNCT-02", "category": "Punctuation", "name": "En-dash misuse", "pattern": "--"},
    {"id": "PUNCT-03", "category": "Punctuation", "name": "Semicolon overuse", "pattern": ";"},
    {"id": "PUNCT-04", "category": "Punctuation", "name": "Curly quotes", "pattern": "curly"},
    {"id": "PUNCT-05", "category": "Punctuation", "name": "Emoji overload", "pattern": "emoji"},
    {"id": "PUNCT-06", "category": "Punctuation", "name": "Bold-lead monotony", "pattern": "**Word:**"},
    {"id": "VOCAB-01", "category": "AI Vocabulary", "name": "delve / delving", "pattern": "delve"},
    {"id": "VOCAB-02", "category": "AI Vocabulary", "name": "tapestry", "pattern": "tapestry"},
    {"id": "VOCAB-03", "category": "AI Vocabulary", "name": "testament", "pattern": "testament"},
    {"id": "VOCAB-04", "category": "AI Vocabulary", "name": "seamless / seamlessly", "pattern": "seamless"},
    {"id": "VOCAB-05", "category": "AI Vocabulary", "name": "foster / fostering", "pattern": "foster"},
    {"id": "VOCAB-06", "category": "AI Vocabulary", "name": "leverage / leveraging", "pattern": "leverage"},
    {"id": "VOCAB-07", "category": "AI Vocabulary", "name": "holistic", "pattern": "holistic"},
    {"id": "VOCAB-08", "category": "AI Vocabulary", "name": "intricate / nuances", "pattern": "intricate"},
    {"id": "VOCAB-09", "category": "AI Vocabulary", "name": "groundbreaking", "pattern": "groundbreaking"},
    {"id": "VOCAB-10", "category": "AI Vocabulary", "name": "revolutionize", "pattern": "revolutionize"},
    {"id": "VOCAB-11", "category": "AI Vocabulary", "name": "underscore / underscores", "pattern": "underscore"},
    {"id": "VOCAB-12", "category": "AI Vocabulary", "name": "landscape (abstract)", "pattern": "landscape"},
    {"id": "VOCAB-13", "category": "AI Vocabulary", "name": "showcase / showcases", "pattern": "showcase"},
    {"id": "VOCAB-14", "category": "AI Vocabulary", "name": "empower / empowering", "pattern": "empower"},
    {"id": "VOCAB-15", "category": "AI Vocabulary", "name": "transformative", "pattern": "transformative"},
    {"id": "VOCAB-16", "category": "AI Vocabulary", "name": "supercharge", "pattern": "supercharge"},
    {"id": "VOCAB-17", "category": "AI Vocabulary", "name": "elevate", "pattern": "elevate"},
    {"id": "VOCAB-18", "category": "AI Vocabulary", "name": "streamline", "pattern": "streamline"},
    {"id": "VOCAB-19", "category": "AI Vocabulary", "name": "synergy", "pattern": "synergy"},
    {"id": "VOCAB-20", "category": "AI Vocabulary", "name": "robust", "pattern": "robust"},
    {"id": "VOCAB-21", "category": "AI Vocabulary", "name": "cutting-edge", "pattern": "cutting-edge"},
    {"id": "VOCAB-22", "category": "AI Vocabulary", "name": "state-of-the-art", "pattern": "state-of-the-art"},
    {"id": "PHRASE-01", "category": "AI Phrase", "name": "ever-evolving landscape", "pattern": "ever-evolving landscape"},
    {"id": "PHRASE-02", "category": "AI Phrase", "name": "it is important to note", "pattern": "it is important to note"},
    {"id": "PHRASE-03", "category": "AI Phrase", "name": "at its core", "pattern": "at its core"},
    {"id": "PHRASE-04", "category": "AI Phrase", "name": "stands as a testament", "pattern": "stands as a testament"},
    {"id": "PHRASE-05", "category": "AI Phrase", "name": "dive deep into", "pattern": "dive deep into"},
    {"id": "PHRASE-06", "category": "AI Phrase", "name": "in conclusion", "pattern": "in conclusion"},
    {"id": "PHRASE-07", "category": "AI Phrase", "name": "unlock the potential", "pattern": "unlock the potential"},
    {"id": "PHRASE-08", "category": "AI Phrase", "name": "the future looks bright", "pattern": "the future looks bright"},
    {"id": "PHRASE-09", "category": "AI Phrase", "name": "let's dive in", "pattern": "let's dive in"},
    {"id": "PHRASE-10", "category": "AI Phrase", "name": "here's what you need to know", "pattern": "here's what you need to know"},
    {"id": "PHRASE-11", "category": "AI Phrase", "name": "in order to", "pattern": "in order to"},
    {"id": "PHRASE-12", "category": "AI Phrase", "name": "due to the fact that", "pattern": "due to the fact that"},
    {"id": "PHRASE-13", "category": "AI Phrase", "name": "despite these challenges", "pattern": "despite these challenges"},
    {"id": "PHRASE-14", "category": "AI Phrase", "name": "not only...but also", "pattern": "not only...but also"},
    {"id": "PHRASE-15", "category": "AI Phrase", "name": "it's not just about...it's", "pattern": "it's not just about"},
    {"id": "SYN-01", "category": "Sycophantic", "name": "Great question!", "pattern": "great question"},
    {"id": "SYN-02", "category": "Sycophantic", "name": "You're absolutely right", "pattern": "you're absolutely right"},
    {"id": "SYN-03", "category": "Sycophantic", "name": "Spot on!", "pattern": "spot on"},
    {"id": "SYN-04", "category": "Sycophantic", "name": "Certainly!", "pattern": "certainly!"},
    {"id": "SYN-05", "category": "Sycophantic", "name": "I hope this helps", "pattern": "i hope this helps"},
    {"id": "STRUCT-01", "category": "Structure", "name": "Triadic parallelism (rule of three)", "pattern": "X, Y, and Z"},
    {"id": "STRUCT-02", "category": "Structure", "name": "Copula avoidance (serves as / stands as)", "pattern": "serves as"},
    {"id": "STRUCT-03", "category": "Structure", "name": "False ranges (from X to Y)", "pattern": "from X to Y"},
    {"id": "STRUCT-04", "category": "Structure", "name": "Elegant variation (synonym cycling)", "pattern": "synonym cycling"},
    {"id": "STRUCT-05", "category": "Structure", "name": "Inline-header vertical lists", "pattern": "**Header:** text"},
    {"id": "STRUCT-06", "category": "Structure", "name": "Title case in headings", "pattern": "Title Case"},
    {"id": "FILLER-01", "category": "Filler", "name": "at this point in time", "pattern": "at this point in time"},
    {"id": "FILLER-02", "category": "Filler", "name": "in the event that", "pattern": "in the event that"},
    {"id": "FILLER-03", "category": "Filler", "name": "has the ability to", "pattern": "has the ability to"},
]
